name: Collect free Gifts

on:
  schedule:
    - cron: "0 14 * * *" # 2:00 PM UTC (10:00 AM ET)
  workflow_dispatch:

jobs:
  get-gifts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
      - name: Install dependencies
        run: npm i
      - name: Claim gifts and update REWARDS.md
        run: npm run start
      - name: Commit and push
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add REWARDS.md
          DATE=$(date +'%m.%d')
          git diff --quiet && git diff --staged --quiet || (git commit -m "$DATE Rewards" && git push)